-- AlterTable
ALTER TABLE "Mesa" ADD COLUMN     "alto" DOUBLE PRECISION DEFAULT 70,
ADD COLUMN     "ancho" DOUBLE PRECISION DEFAULT 70,
ADD COLUMN     "forma" TEXT DEFAULT 'rect',
ADD COLUMN     "posX" DOUBLE PRECISION,
ADD COLUMN     "posY" DOUBLE PRECISION,
ADD COLUMN     "rotacion" DOUBLE PRECISION DEFAULT 0;
